export type FlutterFailureKind = "pub-get" | "dependency-resolution" | "analyzer" | "dart-compile" | "widget-test" | "golden-test" | "build-runner" | "layout-overflow" | "asset-missing" | "platform-channel" | "android-host" | "ios-cocoapods" | "web-build" | "runtime-exception" | "unknown";
export interface FlutterFailureClassification { detected: boolean; kind: FlutterFailureKind; confidence: "low" | "medium" | "high"; summary: string; evidence: string[]; likelyCauses: string[]; recommendedNextCommands: string[]; recommendedFilesToInspect: string[]; risks: string[] }
interface Rule { kind: FlutterFailureKind; confidence: "low" | "medium" | "high"; patterns: RegExp[]; summary: string; likelyCauses: string[]; commands: string[]; files: string[]; risks: string[] }
const RULES: Rule[] = [
  { kind: "pub-get", confidence: "high", patterns: [/Because .* depends on/i, /version solving failed/i, /pub get failed/i], summary: "Flutter/Dart pub dependency resolution failure detected.", likelyCauses: ["Incompatible package constraints", "SDK constraint mismatch"], commands: ["flutter pub get", "dart pub outdated"], files: ["pubspec.yaml", "pubspec.lock"], risks: ["Changing constraints can break generated code or platform builds."] },
  { kind: "analyzer", confidence: "high", patterns: [/error • /i, /info • /i, /flutter analyze/i], summary: "Flutter analyzer issue detected.", likelyCauses: ["Type/lint error", "Missing import", "Invalid API usage"], commands: ["flutter analyze"], files: ["reported Dart source"], risks: ["Analyzer errors usually block safe release."] },
  { kind: "build-runner", confidence: "high", patterns: [/build_runner/i, /Conflicting outputs/i, /part .*\.g\.dart/i], summary: "Flutter code generation failure detected.", likelyCauses: ["Stale generated files", "Invalid annotations", "Generator version mismatch"], commands: ["dart run build_runner build --delete-conflicting-outputs"], files: ["annotated Dart models/providers/routes"], risks: ["Generated code may be stale or inconsistent."] },
  { kind: "layout-overflow", confidence: "high", patterns: [/RenderFlex overflowed/i, /A RenderFlex overflowed/i], summary: "Flutter layout overflow detected.", likelyCauses: ["Row/Column child lacks Expanded/Flexible", "Missing scroll container", "Unbounded constraints"], commands: ["flutter test", "flutter run"], files: ["affected widget"], risks: ["Overflow may be device-size dependent."] },
  { kind: "asset-missing", confidence: "high", patterns: [/Unable to load asset/i, /No file or variants found for asset/i], summary: "Flutter asset resolution failure detected.", likelyCauses: ["Missing asset file", "pubspec assets section mismatch"], commands: ["flutter pub get", "flutter test"], files: ["pubspec.yaml", "assets/"], risks: ["Release builds may omit required assets."] },
  { kind: "platform-channel", confidence: "medium", patterns: [/MissingPluginException/i, /PlatformException/i, /MethodChannel/i], summary: "Flutter platform channel/plugin failure detected.", likelyCauses: ["Plugin not registered", "Native host mismatch", "Channel name/method mismatch"], commands: ["flutter clean", "flutter pub get", "flutter build apk --debug"], files: ["Dart channel caller", "android/", "ios/"], risks: ["May reproduce only on device/platform host."] },
  { kind: "ios-cocoapods", confidence: "high", patterns: [/CocoaPods/i, /Podfile/i, /pod install/i], summary: "Flutter iOS CocoaPods failure detected.", likelyCauses: ["Pod repo/install issue", "iOS deployment target mismatch"], commands: ["cd ios && pod install", "flutter build ios --no-codesign"], files: ["ios/Podfile", "pubspec.yaml"], risks: ["Requires macOS/Xcode to verify fully."] },
  { kind: "android-host", confidence: "high", patterns: [/Gradle task assemble/i, /Android resource linking failed/i, /Manifest merger failed/i], summary: "Flutter Android host build failure detected.", likelyCauses: ["Gradle/AGP/plugin issue", "Manifest/resource issue"], commands: ["flutter build apk --debug"], files: ["android/", "pubspec.yaml"], risks: ["May need native Android triage."] },
];
function evidence(log: string, patterns: RegExp[]): string[] { return log.split(/\r?\n/).filter((line) => patterns.some((pattern) => pattern.test(line))).slice(0, 5); }
export function classifyFlutterFailure(log: string): FlutterFailureClassification {
  for (const rule of RULES) if (rule.patterns.some((pattern) => pattern.test(log))) return { detected: true, kind: rule.kind, confidence: rule.confidence, summary: rule.summary, evidence: evidence(log, rule.patterns), likelyCauses: rule.likelyCauses, recommendedNextCommands: rule.commands, recommendedFilesToInspect: rule.files, risks: rule.risks };
  const detected = /flutter|dart|pubspec|widget|renderflex|riverpod|bloc|cocoapods|gradle/i.test(log);
  return { detected, kind: "unknown", confidence: "low", summary: detected ? "Flutter/Dart signal detected, but no classifier rule matched exactly." : "No Flutter-specific failure signal detected.", evidence: [], likelyCauses: detected ? ["Review first failing Flutter/Dart tool output."] : [], recommendedNextCommands: detected ? ["flutter analyze", "flutter test"] : [], recommendedFilesToInspect: detected ? ["pubspec.yaml", "reported Dart source"] : [], risks: detected ? ["Unknown Flutter failures require manual triage before safe fixes."] : [] };
}
