import { describe, expect, test } from "bun:test";
import { applySkillCorrection, applySkillHistoryAdjustments, determineSkillsForMessage, explainSkillRouting, explainSkillsForMessage, getSubAgentSkillProfile, matchSkillBundles, parseSkillCorrection, SKILL_REGISTRY, SKILL_NAME_TO_FILE } from "../../src/plugin/lib/skill-loader.ts";

describe("plugin skill loader", () => {
  test("routes Android/Kotlin requests to Java-Kotlin skill", () => {
    const skills = determineSkillsForMessage(
      "Fix Android build error in app/src/main AndroidManifest.xml using Jetpack Compose, Room, Hilt, build.gradle.kts, and adb logcat",
    );

    expect(skills).toContain("software-engineering");
    expect(skills).not.toContain("android-kotlin");
  });

  test("keeps JVM language guidance when Kotlin files are mentioned", () => {
    const skills = determineSkillsForMessage("Perbaiki MainActivity.kt di Android app dengan Gradle Android Plugin dan KSP");

    expect(skills).not.toContain("android-kotlin");
    expect(skills).toContain("java-kotlin");
  });

  test("routes release and build prompts to git-guardrails and verification", () => {
    const skills = determineSkillsForMessage("Fix bundleRelease R8 missing class in app/build.gradle.kts with ProGuard rules");
    expect(skills).toContain("software-engineering");
    expect(skills).not.toContain("android-kotlin");
  });

  test("routes Jetpack Compose prompts to Java-Kotlin skill", () => {
    const skills = determineSkillsForMessage("Review @Composable ProfileScreen with LaunchedEffect and collectAsStateWithLifecycle");
    expect(skills).not.toContain("android-kotlin");
    expect(skills).not.toContain("android-compose");
  });

  test("does not route Java backend prompts to Android", () => {
    const skills = determineSkillsForMessage("Fix Spring Boot UserService.java repository bug");
    expect(skills).toContain("java-kotlin");
    expect(skills).not.toContain("android-kotlin");
  });

  test("routes planning workflow prompts to PRD and issue skills", () => {
    const skills = determineSkillsForMessage("Convert this plan into a PRD, acceptance criteria, and GitHub issues with vertical slices");

    expect(skills).toContain("to-prd");
    expect(skills).toContain("to-issues");
  });

  test("routes safety and decision prompts to guardrail skills", () => {
    const skills = determineSkillsForMessage("Challenge my ADR plan with docs before git push and tag release");

    expect(skills).toContain("git-guardrails");
    expect(skills).toContain("grill-with-docs");
  });

  test("does not route generic priority wording to triage", () => {
    const skills = determineSkillsForMessage("Update priority terbaik saja for workflow skills");

    expect(skills).not.toContain("triage");
  });

  test("routes human UI design prompts to human UI skill", () => {
    const skills = determineSkillsForMessage(
      "Buat dashboard frontend React yang tidak terlihat generated by AI dan tetap connect ke backend API",
    );

    expect(skills).toContain("human-ui-design");
    expect(skills).toContain("software-engineering");
  });

  test("routes UI catalog and visual QA prompts to advanced frontend skills", () => {
    const skills = determineSkillsForMessage("Buat katalog pattern dashboard SaaS dan lakukan visual QA screenshot Playwright");

    expect(skills).toContain("human-ui-design");
    expect(skills).toContain("ui-pattern-library");
    expect(skills).toContain("visual-qa-rubric");
  });

  test("explains selected and rejected skill routing decisions", () => {
    const explanation = explainSkillsForMessage("Fix Spring Boot service bug with tests and frontend copy mention");
    expect(explanation.selected).toEqual(expect.arrayContaining([
      expect.objectContaining({ skill: "software-engineering", reason: expect.stringContaining("intent:35") }),
    ]));
    expect(explanation.selected.length).toBeGreaterThan(0);
  });

  test("uses per-agent skill profiles for sub-agent injection", () => {
    expect(getSubAgentSkillProfile("coder", "Fix duplicate class in app/build.gradle.kts")).toEqual(expect.arrayContaining(["software-engineering"]));
    expect(getSubAgentSkillProfile("debugger", "Review architecture and verification for auth API")).toEqual(expect.arrayContaining(["architecture", "verification-discipline"]));
    expect(getSubAgentSkillProfile("frontend", "Review dashboard screenshot visual QA for React frontend")).toEqual(expect.arrayContaining(["human-ui-design", "visual-qa-rubric", "ui-pattern-library"]));
    expect(getSubAgentSkillProfile("researcher", "Research token optimization and context handoff docs")).toEqual(expect.arrayContaining(["codebase-intelligence", "grill-with-docs", "ai-optimization"]));
    expect(getSubAgentSkillProfile("researcher", "Research official Android Gradle docs")).not.toContain("software-engineering");
  });

  test("routes previously orphaned skills from explicit prompts", () => {
    expect(determineSkillsForMessage("Refactor with SOLID and feature flag performance engineering patterns")).toContain("advanced-patterns");
    expect(determineSkillsForMessage("Optimize token usage, prompt efficiency, and model selection for lower latency")).toContain("ai-optimization");
    expect(determineSkillsForMessage("Update .opencode-context.md handoff and session summary for next session continuity")).toContain("context-preservation");
    expect(determineSkillsForMessage("Improve sub-agent delegation and dispatch review delegated work quality")).toContain("delegation-quality");
    expect(determineSkillsForMessage("Fix ESLint, Prettier, tsconfig, and LSP formatter tooling drift")).toContain("developer-tooling");
  });

  test("registry covers all real skills with routing metadata", () => {
    const concreteSkills = Object.keys(SKILL_NAME_TO_FILE).filter((name) => !name.startsWith("systematic-") && !name.startsWith("test-driven-") && !["brainstorming", "writing-plans", "verification-before-completion", "finishing-a-development-branch", "requesting-code-review", "dispatching-parallel-agents"].includes(name));
    expect(Object.keys(SKILL_REGISTRY).sort()).toEqual(concreteSkills.sort());
    for (const [skill, entry] of Object.entries(SKILL_REGISTRY)) {
      expect(entry.routingMode).toBeDefined();
      expect(entry.intents.length).toBeGreaterThan(0);
      expect(entry.samplePrompts.length).toBeGreaterThan(0);
      expect(entry.preferredAgents).toBeDefined();
    }
  });

  test("negative routing blocks api-design-patterns for visual design wording", () => {
    const explanation = explainSkillsForMessage("Buat visual dashboard UI dengan Figma-like polish dan responsive cards for frontend admin");
    expect(explanation.selected.map((item) => item.skill)).toContain("human-ui-design");
    expect(explanation.selected.map((item) => item.skill)).not.toContain("api-design-patterns");
  });

  test("negative routing keeps security below auth-identity on auth-heavy prompts", () => {
    const explanation = explainSkillsForMessage("Implement OAuth JWT login with RBAC auth flow and session policy");
    expect(explanation.selected.map((item) => item.skill)).toContain("auth-identity");
    expect(explanation.selected.map((item) => item.skill)).not.toContain("security");
  });

  test("parses explicit user corrections for skills and agents", () => {
    const correction = parseSkillCorrection("jangan load frontend, pakai react, harusnya researcher bukan oracle");
    expect(correction).toEqual(expect.objectContaining({
      forbid: expect.arrayContaining(["frontend"]),
      prefer: expect.arrayContaining(["react"]),
      agent: "researcher",
    }));
  });

  test("applies session correction override to skill list", () => {
    const corrected = applySkillCorrection(["frontend", "react", "software-engineering"], {
      forbid: ["frontend"],
      prefer: ["react"],
      reason: "pakai react",
    });
    expect(corrected).toEqual(["react", "software-engineering"]);
  });

  test("history adjustments can influence future routing suggestions", () => {
    applySkillHistoryAdjustments({ frontend: -20, react: 15 }, {});
    const report = explainSkillRouting("Fix React hooks bug in TSX component with frontend polish");
    const selected = report.selected.map((item) => item.skill);

    expect(selected).toContain("react");
    expect(report.candidates.find((item) => item.skill === "react")?.contributions.some((entry) => entry.source === "history")).toBe(true);
  });

  test("low-confidence routing falls back to safest core plus domain skill", () => {
    const report = explainSkillRouting("zzz qqq ambiguous maybe");
    expect(report.selected.length).toBeLessThanOrEqual(2);
    expect(report.selected[0]?.reason).toContain("low-confidence fallback");
  });

  test("multi-skill bundles fire for known task families", () => {
    const uiBundles = matchSkillBundles("UI polish and design review for dashboard");
    expect(uiBundles.map((b) => b.id)).toContain("ui-polish");

    const releaseBundles = matchSkillBundles("Prepare release changelog and tag release");
    expect(releaseBundles.map((b) => b.id)).toContain("release-prep");
  });
});
